data_set:
    training_data:
        samples: 1
        high_range: (0.9, 1.0)
        low_range:  (-1.0, -0.9)
        outputs: [1, -1, -1, -1]


    validation_data:
        samples: 200
        high_range: (0.8, 1.0)
        low_range:  (-1.0, -0.8)
        outputs: [1, -1, -1, -1]

neuron:
    number_of_inputs: 2
    activation: bipolar
    weights_range: (-1, 1)
    bias: 1

optimizer:
    loss: least_mean_square
    epochs: 40
    learning_rate: 0.01
    stop_error: 1.4

visualize: True